service: DefenseMultiplierLambda

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-admin-dj
  region: eu-west-1
  stage: dev

functions:
  DefenseMultiplier:
    handler: handler.defenseMultiplier
